dipakkr/A-to-Z-Resources-for-Students

Python.md, README.md
Python Basics
Numpy Tutorial Link
Pandas Tutorial video added
All resources added self-verified and used by me in past.
=> Python Basics | Numpy and Pandas Tutorial added

README.md
added MongoDB User Group to section 7
=> update readme.md - added mug to 7

README.md
added hackerearth's codemonk to 1.7
=> update readmemd-codemonk to 1.7

README.md
startup weekend, delhi technological university to 3
=> added startup weekend, dtu to 3

README.md
- Fixed broken links: 1.2 Machine Learning and 1.4 Backend Development
- Added PyDelhi meetup link
=> Minor additions and fixes

README.md
=> Added HackNY Fellows Program

README.md, new-contributors.md
type: docs
Some missing hackathons and competitions are added
Resolves: #3
=> Added few hackathons and competitions

Python.md
=> Formatting Changed Python.md

README.md
=> PyCon and React Europe

README.md
https://github.com/ZoranPandovski/al-go-rithms
https://zoranpandovski.github.io/al-go-rithms/
His repo is really helpful.
=> AlgoDS in different programming languages

README.md
=> Update README with PyCon link

README.md
=> World business dialogue link fixed

README.md
Fixes #80 and some more links.
=> Fixed a bunch of broken links

README.md
=> Updated Hacktober Meetups in events section.

README.md, new-contributors.md
Added some resources about cloud computing
=> Added cloud resources

README.md, new-contributors.md
Resolved the numbering issues in the conferences table
#91
=> Resolved the numbering issues in the conferences table

projects/ML.md, projects/React.md
=> Add a new branch for Todo Projects

README.md
Make new Scholarship section in Student Benefits and Program and Add Link - https://blog.udacity.com/2018/10/introducing-the-pytorch-scholarship-challenge-from-facebook.html
=> Add Udacity Deep learning Schlorship #92

projects.md
Added few projects for #104 and #105
=> Frontend and backend projects

README.md
=> Added freeCodecamp and codecademy course to frontend web development

projects.md
=> Added a full stack project in projects.md

Python.md, new-contributors.md
=> Add links to  the index of Python.md

README.md
=> Update robocon link

README.md
#130 Added season of KDE and X.org
=> Added Open Source Programs

README.md
type:docs
Updated the conference dates and added few links
Resolves:#9
=> Updated the conference section

README.md
Signed-off-by: knn <kn.neelalohitha@gmail.com>
This PR fixes the broken links "Hackathon Search Portal" and "Startup Summits and Competitions" of "2.Hackathons and Events" in [README.md](https://github.com/dipakkr/A-to-Z-Resources-for-Students/blob/master/README.md).
Issue [#143](https://github.com/dipakkr/A-to-Z-Resources-for-Students/issues/143)
=> Fix broken link in readme.md

README.md
=> Fix broken achor links in readme.md

README.md
=> Add some Google competitions

Python.md
Huge fan of the book and the projects. Will definitely help students understand Python more deeply.
=> Added Automate the Boring Stuff with Python

README.md
Added link to Epicodus Seattle coding boot camp's full online curriculum.
=> Add Epicodus resource link to Additional Links

README.md, new-contributors.md
=> Add new backend recs

README.md
Corrected several typos in README.md #162
=> Corrected typo errors

README.md
Cleaned up README.md documentation of spelling and grammatical errors.
=> Fixed documentation typos

README-pt-br.md, new-contributors.md, projects.md
added translation in Portuguese-Brazil
=> #150 Add Translation in your Language 

translation/README-pt-br.md
=> Translate README.md in Portuguese

ML.md
More resources will be added in the future.
=> ml.md updated

README.md
added bootcamp scholarships to Scholarships section issue #210
=> bootcamp scholarships added

new-contributors.md
=> added myself to new-contributors.md file

README.md
=> Added internship portal resource

README.md
=> fixed link layout

translation/README-pt-br.md
=> Translate README.md in Portuguese [2]

translation/README-pt-br.md
Hi! I'm a newbie hoping to contribute for the #Hacktoberfest2018. The translation from @milaaraujo is superb. But I think we could make the a little better and natural. Here are my proposed changes for issue #192. Don't know if she agrees, though.
Thanks!
=> Improved PT-BR translation

new-contributors.md, translation/README-pt-br.md
There was a **typo** I missed from the last PR for #227. My bad. Should be good now.
Also added myself to contributors list.
=> Fixed typo and added to contributors

new-contributors.md
This repo is really helpful for students like me. I appreciate your effort and thanks for creating it.
=> Adding my introduction : issue #194

CheatSheet.md
the goto heading had a typo of # goto instead of #12 goto.
it is now fixed
=> Updated CheatSheet.md

README.md
update html to html5 in 1.6 as those links better match hlml5
=> update html to html5

new-contributors.md
Converted the old format to use a table format.
=> Convert new-contributor.md to table format. Solve #242

README.md
Adding a couple links to learn from Wes Bos.
=> Adding courses for JS and ReactJS

new-contributors.md
Jendaipou Palmei, student from india.
=> Updated new-contributors.md

README.md
Markup required additional editing before the pipe. Link is currently active.
=> Update readme.md grace hopper link .

README.md
I think this is a typo, :iPhone: does not show emoji on my computer, but :iphone: does.
So I changed :iPhone : to :iphone:
=> Fix iphone emoji in README.md

CONTRIBUTORS.md
Just made all the existing names in CONTRIBUTORS.md  bold!
=> Contributors names font in BOLD

README.md
As it contains multiple links, put in Additional Links.
=>  Add Dev Circle Link 

CONTRIBUTORS.md, new-contributors.md
https://github.com/dipakkr/A-to-Z-Resources-for-Students/issues/241
=> add Jakub Kusiowski to new contributors

CONTRIBUTORS.md, README.md
Added well known Python online Tutorials, ML Research papers, ML Github Repos to follow and few more...
And Added Myself to the Contributors list :)
=> Updated Contributors.md and Readme.md

CONTRIBUTORS.md
Please let me know if there are any issues. Thanks!
=> dedgren-added-to-contributors.md

CONTRIBUTORS.md
50 | Asrst | India | ML Beginner |
=> Add Intro to Contributors list

CONTRIBUTORS.md, projects.md
Added beginner level ml projects
=> Ml projects

CONTRIBUTORS.md
Fixed spelling mistake and several spacing errors to get rid of stars on output.
=> Added to contributors, several edits

CONTRIBUTORS.md
Added my name to the list. Hope to have a memorable Hacktoberfest with everyone ^^
=> Added my name  ^^

CONTRIBUTORS.md, README.md
- Added Competitive Programming book resources. 
- Added Yann LeCun for people to follow 
- Fixed Data "Structures" typo
=> Fixed a typo. Added Algorithms resources.

translation/README-pt-br.md
just small corrections in README file.
=> Formatting README-pt-br.md

CONTRIBUTORS.md
Added a new contributor as requested
=> New CONTRIBUTORS

CONTRIBUTORS.md
=> added avinash as contributor

CONTRIBUTORS.md
=> Added to CONTRIBUTORS

README.md
=> Add more book resources for software craftsmanship

README.md
How could we leave out Richard Stallman from the list of people to follow
=> Added Stallman to List of People to Follow #326

README.md
Contribution for [#326](https://github.com/dipakkr/A-to-Z-Resources-for-Students/issues/326)
=> Add Simmons/Cohn to Top People to Follow

README.md
=> Add js conference in README.md

README.md
=> Add John Resig in Top People to follow

README.md
Added Vernon to People to Follow [#326](https://github.com/dipakkr/A-to-Z-Resources-for-Students/issues/326)
=> Added Vernon to people to follow

CONTRIBUTORS.md
added my details in CONTRIBUTORS.md
=> added entry in CONTRIBUTORS.md

CONTRIBUTORS.md
=> Added a very special contributor

README.md
=> Add entries in People to follow in Readme.md

CONTRIBUTORS.md
=> Add contribution to contributors.md file

CONTRIBUTORS.md, README.md
I added resources for MERN stack Node React and UI please review and merge thank you :)
=> Added resources of Redux for issue #317 and Js html and css

CONTRIBUTORS.md
=> Contributors.md file modified

projects.md
Adds a project for Full Stack Devs issue #208 called Advanced React, Apollo Client, Prisma and GraphQL Yoga.
=> Adds a project for Full Stack Devs #208

translation/README-fa-IR.md
=> Added Persian translate file for README

translation/README-pt-br.md
* Fixed some typos.
* Added some translations.
=> Updated README-pt-br.md

README.md
Added a Paper with code as specified by @dipakkr
=> Update Paper with Code Link in Proper section #387

CONTRIBUTORS.md, README.md
- API documentation for most of the programming languages with offline support
=> Add API documentation

README.md
Adding Miguel Grinberg to Top People to Follow in the README for his contributions to the Python Web Development Pallets Projects libraries.
=> Add Miguel Grinberg to 'Top People to Follow'

README.md
=> [ADD] ryan dahl as people to follow

CONTRIBUTORS.md, README.md
Add freeCodeCamp to Javascript on README.md
=> Add free code camp

README.md
It happens every year in August
=> Add BrazilJS Conference

README.md
Added known types to conferences table.
Removed duplication of conferences.
=> Add known types to conferences

CONTRIBUTORS.md, README.md
Added information for a new Hackathon event, and added myself to the list of contributors.
=> New coding event addition

README.md
I added Junction, which is Europes biggest hackathon.
=> Added hackathon and information

CONTRIBUTORS.md, README.md
Added link to Vue cookbook as a Vuejs resource.
=> Add Vue cookbook to Vue resources

translation/README-de-DE.md
German translation: Table of Contents
=> Inhaltsverzeichnis

CONTRIBUTORS.md
=> Add myFlagAndInfo to Contributors list

CONTRIBUTORS.md, README.md
Added codrops to HTML5 and CSS reference.
Also added name to contributors.md
=> Add codedrops to html5 and css references

projects.md
Play Code Monkey is for teenagers, but I (40yrs) really enjoyed the functional programming aspect of it and it's basically a game. First 20 levels are free. issue #208
=> Issue #208 Added Beginner coding game and Arduino Education

README.md
Added source related to Python programming language
=> Python Added

CONTRIBUTORS.md
I'm a newbie to programming and github, joined hacktoberfest T-shirt challlenge, trying to get 5 pull requests and learn the basics of github as well, please consider my request
=> Contributions

CONTRIBUTORS.md, README.md
=> Fix arxiv-sanity bad link

git-cheatsheet.md
Added introduction, index for more visual appeal.
=> Updated format for visual appearance

CONTRIBUTORS.md, README.md
=> Add a interactive Flexbox page. Nice one

Archive.md, CONTRIBUTORS.md, DataStructuresCheetSheet.md, ML.md, Python.md, projects.md
1. Python.md
2. Projects.md
3. CONTRIBUTORS.md
=> Resources added

CONTRIBUTORS.md
=> adding myself to the list

README.md
Adding FrontEnd Masters website to the student resource list.
=> Add Frontend Masters Resource

CONTRIBUTORS.md, README.md
Hi I added myself as a contributor, hello everyone!
=> Aleks branch added

README.md
Place, Travel Reimbursement and Timeline column data were edited to become more consistent for easier viewing.
Cheers ☺
=> Reformatted Conferences Data for Consistency

README.md
http://connect.tech/
Great resource for web development and design, colleagues of mine went there this year and had great Javascript workshops for all levels of developers.
=> Added Connect.Tech

README.md
Fixed some typos and rest all looks good.
=> Fixed typo mistake

CONTRIBUTORS.md, GSOC.md, README.md
=> New Contributor

README.md
Hope this helps! I love proofreading so let me know if any other documents need a glance.
=> Fixed some grammatical and phrasing issues in initial paragraphs and removed some spaces for stylistic consistency. (closes issue #499)

CONTRIBUTORS.md
I have added myself to contributors list. #328
=> added myself to contributors list

CONTRIBUTORS.md, README.md
I am adding C# learning resource links
=> Add C# learning sources

CONTRIBUTORS.md, README.md
Added Pro Git Book  v2 download link. The Book is free and available in pdf, epub amd mobi formats.
=> Added Pro Git book

README.md
Added two new meetups from Finland to README.
=> Update meetups to README.md

Python.md
Added a link to Python anti-patterns
=> Added a link to Python anti-patterns

CONTRIBUTORS.md, README.md
Here's the link to the resource I've added: [33 concepts every JavaScript developer should know.](https://github.com/leonardomso/33-js-concepts)
=> Add JavaScript Resource

translation/README-it-IT.md
I've added the Italian translation of README.md as /translation/README-it-IT.md
=> Added Italian translation of README.md

README.md
Added a video tutorial by New Boston from which I learnt Python very quickly and efficiently. Hopefully it will help others also
=> Updated README.md by adding a link for python

README.md
Added TechTO to list of conferences
=> added to conference list

README.md
Added 100 days of code connect link to clubs and meetups
=> added to clubs and meetups

CONTRIBUTORS.md
added my own info and fixed a wrong number in the list
=> adding number 165

README.md
=> Added CCC and Bitbucket Education

projects.md
MEOWER - Twitter clone explained
=> Added educational / example project

README.md
=> added to startup news/stories

CONTRIBUTORS.md, README.md
- Added a new resource for Python 
- Updated Contributers.md
=> New branch

CONTRIBUTORS.md
Added my below details in contributors.md file
=> A-to-Z-Resources-for-Students

README.md
=> Added Daniel Shiffman

README.md
Added links in the Developer Clubs and Meetups section
=> Added links in the Developer Clubs and Meetups section

CONTRIBUTORS.md
=> Added my name :)

README.md
added indeed.com to the list of internship portals
=> added to the list of internship portals

README.md
I'm not sure what the numbering/ID significance is (ranking of some kind? If so, the ranking criteria is not clear), so I just added my additions to the end.
=> Add HackNC to list of hackathons

README.md
Add open-source books of Jake Vanderplas
- [A Whirlwind Tour of Python](https://github.com/jakevdp/WhirlwindTourOfPython)
- [Python Data Science Handbook](https://github.com/jakevdp/PythonDataScienceHandbook)
=> Add Python resources

Python.md
Added CSDojo's Channel which provide tips
=> Added CSDOJOS channel

README.md
-Corrected strange line spacing under Node.js
-Corrected FreeCodeCampt to freeCodeCamp
-Added Swift worldwide meetups link
-Added MUD worldwide meetups link
-Adjusted various other spacing, indentations
On branch hacktober-psm-102518
Changes to be committed:
modified:   README.md
=> Add Links, Cleanup Indentation, Fix Typo

README.md
Add node best practices link to list.
=> Add node best practices link

CONTRIBUTORS.md
As in #636 , I added my names to contributor list.
=> Add Leonardo Dominguez name to contributor list.

CONTRIBUTORS.md, README.md
🤜  Partial contribution to #636 .
=> Add SA learning resource

README.md
This commit is related to #462
=> Fix three missing links in README

CONTRIBUTORS.md
=> Hacktoberfest Pull

README.md
Add my favorite resource for learning python
=> #636 Add python learning resource on README

translation/README-de-DE.md
The greatest Hackathon in Paradise Island Mauritius.
=> Added annual hackathon Mauritius

CONTRIBUTORS.md
added my info into contributors list.
=> add my name into contributors

CONTRIBUTORS.md, README.md
This PR adds another PHP resource. Happy Hacktoberfest!
=> Add "PHP: The Right Way" to PHP resources

README.md
[Megathon](https://megathon.in/) is a 2 day hackathon jointly organized by IIT-Hyderabad and IIIT-Hyderabad.  I have added it to the list of hackathons.
=> Added Megathon to list of hackathons

CONTRIBUTORS.md, README.md
So far I've mostly focused on the first part of the document (Coding Resources).  I started by trying to make the content more clean and readable by adjusting the lists indentation, formatting the comments and removing the emoji from the titles. 
I think it looks more polished not to use the emoji there because some of them didn't seem related to the content and were reused in different titles. Also, at least on Windows, the emoji size messes up with the line spacing. But if you guys think it looks better with it I can re-add them, no prob.
That said, I did use emoji to replace messages written repeatedly through the doc like "for begginers" (👶) and "paid" (💲).
I also renamed some of the resources to make it clearer what's the source (Udemy, Udacity, YouTube, etc.) or what is it about. …
=> #604 README.md clean up and formatting

Blockchain.md, CONTRIBUTORS.md
Added some great references for blockchain enthusiasts.
=> Hacktober contribution

CONTRIBUTORS.md
Following up from my contributions in #567.
=> Add self to CONTRIBUTORS

CONTRIBUTORS.md
=> Update: Added Name

Blockchain.md, CONTRIBUTORS.md, Machine_cleansheet.md
Changes to Contributors.md
Changes to machine_cleansheet.md
Changes to blockchain.md
=> Added Contributions

README.md, translation/README-de-DE.md
Developers Conference Mauritius By MSCC! Visit paradise island Mauritius and attend Annual Developer Conference
=> Developers Conference Mauritius By MSCC

Android.md
Help everyone to learn Kotlin language from the reference
=> add kotlin references

README.md
The course is created by Daniel Shiffman.
=> Add beginner course Foundations of Programming in JavaScript

git-cheatsheet.md
Adding some information and basic commands for git reflog to git-cheatsheet.md.
=> Adding git reflog information

CONTRIBUTORS.md, README.md
Linked to my github in contributors.md
=> Added myself to list of contributors #328

DataStructuresCheetSheet.md
Updated the data structure cheat sheet with reference to  some new free book resources
=> Updated data structure cheat sheet

CONTRIBUTORS.md
Added my contribution, hopefully it works this time.
=> added contribution

CONTRIBUTORS.md
also corrected markdown for one earlier entry
=> hactoberfest added my name in contributors

README.md
Replaced Azure for Students with Microsoft Imagine pack which includes Azure for students and other tools and subscription offers for students.
=> Replaced Azure for Students with Imagine pack

README.md
I believe it is one of the best resources for Android Development
=> Added Caster.io in Android Development section

Blockchain.md, ML.md, Python.md
also added one of the best lectures by Ashish Tendulkar - visiting faculty at IIT Bombay and former researcher at Google India for Machine Learning in Tensorflow.
=> added few really important & interesting datasets

CONTRIBUTORS.md, README.md
Added Zen of Programming link to README and personal information to CONTRIBUTORS.
=> Tiffany new branch

Python.md
Added the Web development frameworks  and Some Desktop  development Frameworks used in Python
=> Added Web and Desktop development Framewroks

CONTRIBUTORS.md
as per https://github.com/dipakkr/A-to-Z-Resources-for-Students/issues/496
=> shamelessly added myself to CONTRIBUTORS.md for hacktoberfest

Blockchain.md
A tip those who're not aware of bitcoin and blockchain
=> Blockchain and Bitcoin

CONTRIBUTORS.md
=> me agregué al archivo

CONTRIBUTORS.md, README.md
=> added new nodejs resource

CONTRIBUTORS.md
Added Keyur Canji as contributor
=> Added contributor

README.md
Add [LearnGitBranching](https://learngitbranching.js.org/), a great Git visualization learning tool.
=> docs: Add LearnGitBranching resource

README.md
Add Learning JavaScript Design Patterns resource. This is a great book written by Addy Osmani and available for free online!
=> docs: Add Learning JavaScript Design Patterns resource

README.md
Add Guido van Rossum python creator and Yukihiro Matsumoto Ruby Creator to People to follow
=> Add Guido van Rossum and Yukihiro Matsumoto 

ML.md
Added another interesting data set(,with the link) from Kaggle, that contains data related to stars, classifying them as Pulsar or non-Pulsar stars. It is based on the data collected during High Time Resolution Universe Survey. Also added one of the most celebrated deep learning scientist and entrepreneur. He is also the instructor of the course - Deep Learning Specialization in Coursera.
=> Added a data set and another celebrity.

README.md
Added additional CSS related resources
=> Add CSS Resources

README.md
Added a new website to php, js, html, css and bootstrap list with beginner friendly tutorials.
=> Added Web Dev resources

README.md
CodeSignal (formerly called CodeFights) hosts various contests of short/long challenges to compete against coders/bots.
=> added CodeSignal to section 1.7

CONTRIBUTORS.md
Shameless addition to contributors list <3.
=> Updated Contributors

README.md
👋 hey folks,
Came to make a PR to [do my job](https://twitter.com/jna_sh/status/830073044865576960) and correct the name of the GitHub Campus Experts program.  Whilst I was here, I added the $100 Azure offer to the student packs section, and bought all of Microsoft's offers under one bullet point to reduce confusion. 
Cheers!
=> Corrected Campus Experts title, tidied up Microsoft packs

Machine_cleansheet.md
Removed the relative links to nowhere causing issue #686
=> Remove md links to nowhere causing 404

ClanguageCheatSheet.md
improved the readability of the file by changing the format and changed minute other details.
=> fixed #756 issue

README.md
Fixed a typo Angualr => Angular
=> Typo Angualr => Angular in README.md

CONTRIBUTORS.md
Added Name to CONTRIBUTORS.md #636
=> Added Name to CONTRIBUTORS.md

CONTRIBUTORS.md, README.md
Aded myself to the contributors.md and added an event in the NL
=> Added myself to contributors and added an event

CONTRIBUTORS.md
Added a new contributor to the contributors list.
=> Added a new name

projects.md
=> Adding Laravel to backend projects

Python.md
=> Suggestion to add three more Misc Python links

README.md
Not sorted and will likely add additional commits to remove events that have ended or have retired pages. 
WIP but will fix #807
=> Update hackathons with dates

CONTRIBUTORS.md
Added myself to the contributors file.
=> Added myself to the contributors file.

README.md
Added two good NODE.js resources.
=> Added two good node resources.

ClanguageCheatSheet.md
This PR adds the following badges to [README.md](https://github.com/dipakkr/A-to-Z-Resources-for-Students/blob/master/README.md) : 
1.Licence Badge
2.PR Welcome Badge
=> Update README.md with badges

ClanguageCheatSheet.md
Adds macros section explaining macro definition, commonly used keywords, and types of macros.
=> Updates ClanguageCheatSheet.md with macros section

CONTRIBUTORS.md
=> Add name to CONTRUBUTORS.md

Nodejs.md
Added resources about the event loop in the nodejs file.
=> Added resources about the event loop in the nodejs file.

README.md
Adds 3 excellent PHP resources for basic to intermediate learners.
=> Adds 3 excellent PHP resources

README.md
Added links to Rob Miles' C# "Yellow Book" and the free MSDN C# fundamentals course on Channel9
=> Added two good and free C# resources

CONTRIBUTORS.md, projects.md
Make a Hacktoberfest Pull Request #636
=> Make a Hacktoberfest Pull Request #636

README.md
This is in some cases better than php the right way as it shows you a lot of what to avoid in php.  It's very easy to read and I learned alot from it.
=> Php the wrong way

README.md
Added a good article on the Mongoose Populate method, which is really useful if you are designing a database layout with relational data.
And an article on Express.js production best practices.
References #498
=> Add mongoose populate article & Express.js article

README.md
I have add references from Vue.js News and Made With Vue.js.
=> Add refs from vue.js news and made with vue.js

translation/README-pt-br.md
Realization of some translations and corrections of writing errors.
=> Realização de algumas traduções e erros de escrita

CONTRIBUTORS.md, README.md
Good material for beginners in Mongo and very complete
=> Added material for MongoDB

README.md
Inova is an incubator/startup program from UFRN in Natal/Brazil. I added it to the list of incubators.
=> README.md: Add "Inova Metrópole" to incubators section

CONTRIBUTORS.md, README.md
An awesome collection of notes for programmers. A must have repository.
Thanks.
=> Add programming notes for professionals repo

README.md
=> add new Git resource

translation/README-de-DE.md
Fixed dead image link in german readme translation.
=> Fixed image src in german translation

CONTRIBUTORS.md
Added personal info - location, occupation, and Github. Also correct spelling of another user.
=> Added myself to list of contributors

translation/README-es.md
Forgot to translate another sentences. Still outdated.
=> Update README.md Spanish translation 2.0

Python.md
flask CS50 youtube link contained time.
=> Flask link fix

ClanguageCheatSheet.md
=> Added a video tutorial

README.md
Removed copy-pasted 'Verified account' from 'Top person to follow'
=> Fix copy/paste typo

CONTRIBUTORS.md, README.md
=> Added info on how to audit coursera courses

ClanguageCheatSheet.md
This is an attempt to fix #1071.
There are some weird characters under section 2 **Allowed Character Set** like `â€¦..`.
I'm not sure what to do about these.
=> Fix C Language Cheat Sheet Formatting

README.md
updated Developer Clubs and Meetups
=> Enhanced Developer Clubs and Meetups Section

README.md
- Went through Conference list in README and made updates to reflect which events have passed
- Updated a couple of conference websites
I would **love** to go through this again to organize so it's easier to peruse! Perhaps alphabetize event/conference names since many of them will repeat year after year.
=> Conference list updates #1084

CONTRIBUTORS.md, CheatSheet/Ruby-CheatSheet.md
=> Add Ruby methods cheatsheet

CONTRIBUTORS.md, README.md
=> Add Seedstars Startup Program

CONTRIBUTORS.md, README.md
Added:
- Technical and scientific conferences 
- Hackathons and events in Germany, Canada, USA & Mexico
- Mexico's flag and myself to the list of contributors 
- Hackathon in St. Gallen
=> Updating resources

README.md
=> Added ML cheatsheets for Stanford's CS 229

CONTRIBUTORS.md, README.md
the links in docker section have been now made a little descriptive.
user will be able to understand where the links will take them.
fixes #1111
=> Added more detail in docker section

PULL_REQUEST_TEMPLATE.md
[Beginner-friendly Javascript course](https://sabe.io/classes/javascript)
=> Add super helpful javascript resource

CONTRIBUTORS.md
I did my first contribution on GitHub :) by adding my name to the list of contributors in my branch
=> added my name to list of contributors

CONTRIBUTORS.md, README.md
These days graphic designing has become an important job field and many people love to do that. 
Therefore for some budding desginers, resources to help them grow.
=> Add design tools/resources

README.md, translation/README-de-DE.md, translation/README-es-latam.md, translation/README-es.md, translation/README-fa-IR.md, translation/README-ger.md, translation/README-it-IT.md, translation/README-ko.md, translation/README-pt-br.md, translation/README-pt-pt.md, translation/README-rus-RU.md, translation/README-zh-TW.md, translation/READMEgr-GR.md
Added the new Call for Code competition links.
=> Add Call for Code 2019 details.

README.md
[Beginner-friendly Javascript tutorial](https://sabe.io/classes/javascript)
=> Added WWDC and WWDC Scholarship

README.md
Add Free Microsoft Office 365 for Students
- [Free Microsoft Office 365 for Students](https://www.microsoft.com/en-us/education/products/office/default.aspx)
Free Microsoft Office 365 + OneDrive (Free 1TB), etc.
=> Add Free Microsoft Office 365 for Students

GSOC/GSOC.md
added GSOC guide video link in GSOC.md
=> added gsoc guide video link

README.md
Added three exceptionally efficient and widely acclaimed books of the language R.
=> Added three new R language resources

README.md
I have enumerated a couple of scholarships with their links in the description. (No. 6 to 14)
The above addresses issue #1184. 
Please review.
Thanks!
=> Updation of READMe - Added info on scholarships

README.md
=> fixes #1243 ml link broken

README.md
Added the most reputed international internship programs to fix issue #1256
=> International internships

README.md
The link to backend roadmap was broken.
=> Broken Link

README.md
Its a great resource for react.
=> adds scrimba to react resources

CONTRIBUTORS.md
=> Adds to contributors file

README.md
=> Add The Odin Project to Fullstack Web Development Section

README.md
Dmitry Soshnikov's website has many good articles for understanding the JavaScript which I recommend everyone who would like to know deeper the JavaScript to read.
=> add-js-resource

README.md
=> Add Udacity Bertelsmann Technology Scholarships Program 2020

README.md
best sites for getting ready with aptitude.
=>  Top sites for APTITUTE PREPARATION FOR PLACEMENTS

README.md
Learn You a Haskell is an excellent resource for beginners looking to learn Haskell. 
It is a available for free online on the site: http://learnyouahaskell.com
=> add haskell resource: Learn You a Haskell

CONTRIBUTORS.md, README.md
Hello Deepak Kumar.
I´m openning a PR to include a awesome reference do C# Language. 
I think it will help many students to learn design patterns in a very easy way.
Fell free to merge the PR.
Best Regards.
=> added link to learn C# Design Patterns the easy way

README.md
Book is last updated in 2015 but main focus of book is understanding data structures (basics and more advanced). Also there are implementation for data structures with pointers and without pointers.  Book is made out of 3 parts. Basics, intermediate and advanced stuff so it's good for more advanced developers if they want to skip basics and take on intermediate or advanced part right away.
=> Added online book for C++

README.md
This website offers information about computer sciences, its specialized fields and provides detailed statistics and help for people wishing to know about the world of computer science.
=> Added useful website regarding computer science

Python/Python.md
The course content is awesome for the beginners. It covers whole lot topics from Installation, Type and Values, Conditional, Operators, Loops, Functions, Structured Data, Classes, Exceptions, String Objects, File I/O, Modules etc.
It can be taken for free as well, if applied for "Free one month trail on LinkedIn Learning". 
I myself have taken this course and found very useful. Post Link - https://www.linkedin.com/posts/rudyredhat_linkedinlearning-oppurtunity-revise-activity-6714898326887776256-EO3b
=> Adding Python Content - Python Essential Training

Intern Abroad/Resources:, README.md, Research Internship (All)
All Link for all major Research Internships in India and Abroad.
=> Research Internship (India /Abroad)

CONTRIBUTORS.md, IoT/Arduino.md, IoT/IoT.md, IoT/RaspberryPi.md, Robotics/ROS.md, Robotics/Robotics.md
Added Resources to get Started in IoT and Robotics for now, will be soon!
=> added IoT and Robotics

Android/Android.md
These courses are offered by Google on Udacity and are the most recommended. You can also find similar code labs here: https://developer.android.com/courses/
=> Appended courses for Android Development in Kotlin

CheatSheet/DataStructuresCheatSheet.md, README.md
In the Readme section, I have updated the events section with the recent competition that I came across and the hackathon finder website. And in the DSA cheatsheet folder, I have attached the link to Cracking the coding interview book ( It is one of the best books to crack the technical interviews.)
=> Updated the README and the Cheatsheet folder

README.md
Hey, I am a Beta MLSA. The MSP program is now MLSA and it's open all year round and students are taken in quarterly. Please update it! More Details [here](https://www.youtube.com/watch?v=JcSwk7-N-_I)!
Thanks!
=> Updated Microsoft Learn Student Ambassadors (MLSA)

Projects/Projects.md, README.md
Added all Of the necessary Stacks for Full-stack Web Development and also described their types.
Added some more Useful Projects For beginner Friendly and also some to Sharpe up their Skills.
=> Updating Full-stack Web Development

README.md
It is an Open-source & easy to use Free Bootstrap 5 Admin Template with elegant design & unique layouts. Sneat admin offers an Attractive Dashboard, enhanced bootstrap 5 components, AUTH Pages, Tables, Ready to use cards & form layouts.
You can build any type of web application. For instance, you can create:
- SaaS platforms
- Project management apps
- Ecommerce backends
- CRM systems
- Analytics apps
**Features:**
- Based on Bootstrap 5
- Basic Table
- Basic Cards
- Forms
- 1 Dashboard
Demo: https://www.themeselection.com/demo/sneat-bootstrap-html-admin-template-free/html/
Download: https://themeselection.com/products/sneat-free-bootstrap-html-admin-template/
=> Added Sneat Free Bootstrap 5 HTML Admin Template

README.md
Removed expired links and updated upcoming conferences. Also included a few new resources for students.
=> Reorganized and updated the Conference list

README.md
Added useful data science related websites.
=> Updated Data Science Websites to follow

README.md
Added python learning resources
=> Added resources under Python

README.md
I added Codementor Events to Events, fixed the link, and removed global.
=> Added Codementor Events to Events

Python/Python.md
Added a new resource under 'Python Basics' that has everything a beginner should need in order to learn python language.
=> Added a new resource

README.md
Hey, I have added a helpful reference link for the C tutorial in the C language section that I think will best add to your content and give your readers a more diverse understanding of the topic. I hope you will like this. Thank you.
=> Added one useful resource for C

README.md
Hey @dipakkr , can you please merge this pull request and label it as hacktoberfest or hacktoberfest-accepted as a part of my hacktoberfest 2022 contributions
I have added HTML,CSS and JavaScript Cheatsheet links.
I have also added Campus Ambassador Program opportunity by Geeksforgeeks
=> Added HTML,CSS and JavaScript Cheatsheet, Campus Ambassador Program by GFG

Projects/Projects.md
Added weather project in frontend dev and Movie recommender system in ML
=> Added weather project and Movie recommender system

README.md
Hey, I've added a useful C++ reference link in the C++ section, I think this will best add to your content and give your readers a more diverse understanding of the topic. I hope you will like this. Thank you.
=> added a helpful resource

Python/Python.md
These new resources include a comprehensive list of Python commands, functions and modules, as well as helpful tips and tricks to make programming in Python easier and more efficient.
=> I've added a new resource to this repos.

README.md
New interview questions link for deep learning under "Best Online Courses" in "Deep learning".
=> Adding a new link for deep learning

Python/Python.md
Added a new resource link for python. I came across this article while looking for resources to learn about python. In my opinion, this quote will strengthen the content of this article. I hope my contribution will be useful to other learners.
=> Added one Useful Link

README.md
It is an Open-source & easy-to-use Free Bootstrap 5 Admin Template with elegant design & unique layouts. Materio admin offers an Attractive Dashboard, enhanced Bootstrap 5 components, AUTH Pages, Tables, Ready-to-use cards & form layouts.
You can build any type of web application. For instance, you can create:
- SaaS platforms
- Project management apps
- Ecommerce backends
- CRM systems
- Analytics apps
**Features:**
- Based on Bootstrap 5
- Basic Table
- Basic Cards
- Forms
- 1 Dashboard
**Demo:** https://www.themeselection.com/demo/materio-bootstrap-html-admin-template-free/html/
**Download:** https://themeselection.com/item/materio-free-bootstrap-html-admin-template/
**Github:** https://github.com/themeselection/materio-bootstrap-html-admin-template-free
=> Added Materio Free Bootstrap 5 Admin Template

README.md
Added CompSciLib to Computer Science resources.
=> Added CompSciLib to CS Resources

README.md
Materio Free Vuetify VueJS 3 Admin Dashboard Template – is the most developer-friendly & highly customizable Admin Dashboard Template based on Vuetify.
Furthermore, you can use this innovative Free admin template to create eye-catching, high-quality, and high-performing single-page applications. Besides, your apps will be completely responsive, ensuring they’ll look stunning and function flawlessly on desktops, tablets, and mobile devices.
In addition, it comes with the following features :
- Latest VueJS 3, Vuetify 3
- Vite 5
- Utilizes Vue Router, VueUse
- Available in both TypeScript & JavaScript versions
- 1 Dashboard
- Remix Icons
- Basic cards
- Fully Responsive Layout
- Organized Folder Structure
- Clean & Commented Code
- Well Documented
=> Added Materio Free Vuetify VueJS Admin Template

CONTRIBUTORS.md, README.md
I work for MathWorks and added a few useful links for students learning MATLAB.
=> Additional MATLAB resources

ML/ML.md
The TF image in the previous version was not loading because of changes to the file structure. I changed the link so that it would load correctly.
=> Updated ML.md to replace a dead image link.

README.md
Add LabEx to Coding Resources
I work at LabEx, a unique learning platform that has delivered over 6,000 hands-on labs over the past seven years. Unlike online coding platforms, LabEx offers free hands-on labs in Linux, Git, Programming, Docker, DevOps, and Cybersecurity. It provides an online hands-on environment where users can practice online and automatically validate their solutions.
This repo is a great resource. Please let me know if any changes are needed.
=> Add new hands-on learning platform to Coding Resources

CONTRIBUTORS.md, README.md
- OneCompiler is a free online compiler. It helps users to write, run and share code online for more than 70 programming languages & databases, Including all popular ones like Java, Python, MySQL, C, C++, NodeJS, Javascript, Groovy & HTML
=> Add OneCompiler to Online Platforms

CONTRIBUTORS.md, README.md
Added https://cloudcredits.io/ (GitHub: https://github.com/DUALSTACKS/cloudcredits.io)
A fully open-source collection of cloud/SaaS/all kinds of credits and perks to experiment and build.
=> docs: added cloudcredits.io

README.md
The Domain 
https://www.theschool.ai/courses/decentralized-application/ is inactive and is up for sale
Resloved issue #1457
=> Removed The Invalid link for theschool.ai
